### ISSUE TITLE
[Feature] Revamp the throttle msg

### ISSUE THREAD

**Issue by PBechon** [Simpit-team/KerbalSimpitRevamped-Arduino#1]
I feel that sending a throttle command is unnecessarily more complicated than other command (like rotation and translation) since there is no struct defined. One has to figure out for instance than sending for sending one value the correct message size (in byte) is 2 and that the number should be send as uint16.

I would suggest to create a struct for throttle only, containing only one value, and all the needed helper to be able to call

```
throttleMessage throttle;
throttle.throttle = 100;
mySimpit.send(THROTTLE_MESSAGE, trans);

```

**Comment by LRTNZ** [comment]
I see your point - will take a look into this.

**Comment by PBechon** [comment]
In fact the modification was quite small. I did a pull request to put it in, and I added an example with it (that I used to test it).

**Comment by LRTNZ** [comment]
Thanks! Will test it shortly, along with the target fix on the other repo.

**Comment by LRTNZ** [comment]
Just waiting on a couple of tweaks and answers to my questions/suggestions 😄

**Comment by PBechon** [comment]
What tweaks and suggestion ? I did not see those I think, I might have missed them.

**Comment by LRTNZ** [comment]
> 
> 
> What tweaks and suggestion ? I did not see those I think, I might have missed them.

Sorry, I forgot to hit submit on the review I did 😅

**Comment by LRTNZ** [comment]
This has been solved!
